[package]
name = "promptpal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
walkdir = "2.4.0"
tempfile = "3.8.1"
tiktoken-rs = "0.5.8"
tokio = { version = "1.34.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["serde"] }
